### ISSUE TITLE
Adapt the binder-tests to interact with actual interceptors instead of relying on test channels 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-rabbit#108]
As a developer, I'd like to refactor the binder tests to use the actual interceptors, so we can validate the real functional abilities as opposed to merely relying on test channels for the message in/out.

**Comment by olegz** [comment]
Given that this issue has to be handled at the _AbstractTestBinder.bindProducer/Consumer_ closing it in favor of https://github.com/spring-cloud/spring-cloud-stream/issues/1111
