### ISSUE TITLE
The dead queue already exist,but spring rabbit not found.

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-rabbit#112]
_From @ExtremeYu on November 27, 2017 14:43_

![image](https://user-images.githubusercontent.com/16620268/33272105-1fe989c8-d3c4-11e7-92af-9a406ce24d7f.png)

![image](https://user-images.githubusercontent.com/16620268/33272197-6a89d046-d3c4-11e7-8bb1-78292fda3709.png)

![image](https://user-images.githubusercontent.com/16620268/33272275-9a17fdba-d3c4-11e7-978e-8f310411cb3e.png)

_Copied from original issue: spring-cloud/spring-cloud-stream#1149_

**Comment by sabbyanandan** [comment]
_From @ExtremeYu on November 27, 2017 15:18_

floow the doc to recive the dead queue message ,but failed to statrt

**Comment by sabbyanandan** [comment]
Hi, @ExtremeYu. It appears you're using the [DLQ-processing sample](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/05079c3976275867551c5dc290b597f3b5301d82/spring-cloud-stream-binder-rabbit-docs/src/main/asciidoc/dlq.adoc) from the docs. It has no direct relevance to Spring Cloud Stream's programming model, though. It might be better for us to review if you can share a sample project and configurations.

**Comment by ExtremeYu** [comment]
maybe i add `spring.cloud.stream.rabbit.bindings.push_recevier.consumer.autoBindDlq=true`  option to consumer and provider both  ,so the error message no longer appear,

**Comment by sabbyanandan** [comment]
Thanks for the update.
