### ISSUE TITLE
How to use an existing exchange and queue

### ISSUE THREAD

**Issue by TonyLiu0112** [spring-cloud/spring-cloud-stream-binder-rabbit#114]
When I read the document, I saw the document said:

>```properties
>spring.cloud.stream.bindings.input.destination=myDestination
>spring.cloud.stream.bindings.input.group=consumerGroup
>```
>"This configuration creates an exchange myDestination with queue myDestination.consumerGroup bound to a topic exchange with a wildcard routing key #".

If I do not want the framework to create exchange and queue for me, I would like to use an existing exchange and queue, how do I configure it?

If in a cluster environment, how do I avoid the problem of consumers consuming the same queue message repeatedly?

Thank you very much for the answer

**Comment by olegz** [comment]
Have you looked ate `bindQueue` as well as other configuration options available? - https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.M3/reference/htmlsingle/#rabbit-binder-properties

**Comment by garyrussell** [comment]
To prevent the binder from declaring the exchange...

`....consumer.declareExchange=false`

The upcoming 1.3.1.RELEASE will [support consuming from an existing queue via the `queueNameGroupOnly` property](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/100)

>If in a cluster environment, how do I avoid the problem of consumers consuming the same queue message repeatedly?

Consumers in the same group compete for messages, only one instance will get the message.
