### ISSUE TITLE
autoBindDLQ on TopicExchange

### ISSUE THREAD

**Issue by Vadus** [spring-cloud/spring-cloud-stream-binder-rabbit#122]
Setting autoBindDLQ=true will cause the binding of a dead-letter-queue to the DirectExchange DLX ('DLX', if no other naming settings are configured)

In my target rabbit there is a global DLX as TopicExchange, which I want to use. With this autoBindDLQ will lead to the error `[AMQP Connection xxx.xxx.xxx.xxx:xxxx] o.s.a.r.c.CachingConnectionFactory : Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'DLX' in vhost '/': received 'direct' but current is 'topic', class-id=40, method-id=10)`

Is it possible to make the ExchangeType of DLX, when using autoBindDLQ, configurable?

**Comment by olegz** [comment]
@Vadus could you specify version of spring-cloud-stream and binder you are using?

**Comment by Vadus** [comment]
The usage of DirectExchange is implemented in spring-cloud-stream-binder-rabbit-core-1.3.0 org.springframework.cloud.stream.binder.rabbit.provisioning.RabbitExchangeQueueProvisioner:269

**Comment by sabbyanandan** [comment]
This has been addressed via: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/commit/75ebb08479de1fcfe514c557e35abfcac3acd5f6
