### ISSUE TITLE
Configuring the SimpleMessageListenerContainer in RabbitMessageChannelBinder

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-stream-binder-rabbit#139]
Hello
As for today, only a [subset ](https://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/html/_rabbitmq_binder.html#_rabbitmq_consumer_properties) of `SimpleMessageListenerContainer`  properties are supported when configuring the container. Please support all properties  from `spring.cloud.stream.rabbit.bindings.<channelName>.[consumer/producer]` namespace.
Thanks

**Comment by olegz** [comment]
@jvmlet I am not exactly sure what do you mean when you say _"...all properties from spring.cloud.stream.rabbit.bindings.<channelName>.[consumer/producer] namespace..."_ - we do support all that we expose. 
If you believe there is/are additional configuration property(ies) you'd like us to expose, please specify which one(s) and we can discuss them in isolation as there may be reasons why some properties should/shouldn't be exposed and therefore we can not blanket it.

**Comment by jvmlet** [comment]
@olegz ,I'm interested in properties that control the concurrency settings , like  `consecutiveActiveTrigger` and   `startConsumerMinInterval`

**Comment by olegz** [comment]
Sure we can look into that. What would help if you could elaborate on your use case a bit as to why you need them to be exposed.
Basically `SimpleMessageListenerContainer` is indeed a generic component exposed a variety of configuration properties, however in spring-cloud-stream it's usage is primarily internal and tailored to the specific set of use cases, hence my question (to ensure it the extra properties doesn't expose something that binder wasn't designed to do in the first place).

Anyway, the request is accepted and we'll be addressing it in some form in 2.1 line

**Comment by jvmlet** [comment]
Thanks, @olegz 
We have our custom CTR launcher that reads messages from rabbit MQ and launches the CTR via rest endoint. As CTR launch  is non-blocking, we use `tasks-event` exchange to block the consumer and aknowladge when the task is completed. The stream is deployed in CF and this is how we throttle the number of cuncurrent CTRs.
I want the CTR to  be launched  immedialtely if the cuncerency is not the max instead of waiting 10 (default) `consecutiveActiveTrigger`.
If I'm reinventing the wheel and there is another OOTB approach to throttle the number of running CTRs, will be glad for poiting the docs.
Thanks
