### ISSUE TITLE
Enhance binder to expose queue's metrics at runtime

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-stream-binder-rabbit#147]
It would be good addition to have binder expose queue metrics to allow dynamic scale up of consumers to increase message processing throughput based on consumer utilization rate of the queue/exchange its bound to.

I am thinking that spring cloud stream binder rabbit could fetch and expose consumer utilization rate as metrics. This would allow spring cloud stream application to be deployed with consumer utilization rate metric be bound to kubernetes horizontal pod autoscaler. This way, k8 pod autoscaler will dynamically scale up or down based on consumer rate utilization and spring cloud kubernetes deployer can provider min and max properties to be set in deployment horizontal pod autoscaler spec.

**Comment by garyrussell** [comment]
You can use RabbitMQ's REST api to get all that information. https://github.com/rabbitmq/hop

>QueueInfo{vhost='/', name='4254c066-6404-4307-a233-b31826ed5fef', durable=false, exclusive=false, autoDelete=true, arguments={foo=bar}, node='rabbit@localhost', exclusiveConsumerTag='null', state='null', policy='null', idleSince='null', diskReads=0, diskWrites=0, memoryUsed=0, messageBytes=0, messageBytesPersistent=0, messageBytesRAM=0, messageBytesReady=0, messageBytesUnacknowledged=0, totalMessages=0, messageStats=null, totalPersistentMessages=0, totalTransientMessages=0, messagesReady=0, messagesReadyDetails=null, messagesUnacknowledged=0, messagesUnacknowledgedDetails=null, consumerCount=0}

**Comment by mv78** [comment]
@garyrussell garyrussell 
It would be good to incorporate this into binder interface and have it available for micrometer and or actuator. The reason I am saying is that, even thou we can build custom solution in our own stream apps, the starter apps and community apps would not have this available or would provide its own custom way of doing it. Since this becomes cross-cutting concern, it would be best if binder provided all the needed facility and expose such metrics so that all spring cloud stream starter projects and starter apps would have it out of the box.

**Comment by mv78** [comment]
@olegz 
"Not entirely true. Binder doesn't have to create queues and can (and in a lot of cases will) bind to existing destinations created by administrators." - I agree but the code is in the binder to create queue if one is missing and property is enabled to create queue. 

"Also, keep in mind that in theory and practice a destination can have multiple consumers. If so how does one should treat the app-exposed metric since in that case they will not represent true data corresponding to a particular app." - The metric I am proposing is not for metric aggregation purpose but for platform autoscaling purposes. This metric would be used to autoscale the consumer app bound to the destination. If there are multiple apps (i.e. different deployments of consumer bound to same destination) than each one would receive the destination queue's consumer rate to pass it to autoscaler of the platform to know if that consumer needs to scale up. I understand it introduces challenge if existing metric aggregation mechanism is used. However, if binder can expose an endpoint that exposes destination queue metrics (i.e. obtained via rabbitmq REST Template) and not using actuator or Micrometer since we are not aggregating or monitoring this metric but only using it for autoscaling purpose.

**Comment by artembilan** [comment]
I wonder if this is helpful here: http://www.rabbitmq.com/blog/2018/04/10/rabbitmq-java-client-metrics-with-micrometer-and-datadog/. The point is that RabbitMQ Java Client does have a native support for Micrometer. So, that should not be so hard to the metrics through Spring Boot Actuator.

**Comment by olegz** [comment]
Well, as a framework developers we have to think of all possible cases and that includes multiple consumers and non-spring-cloud-stream consumers.
Also, auto-scaling is a whole other question and could/should not be addressed by simply checking the rate or messages. It's a far more complex issue when it comes to Messaging. Take message ordering for example and how a second consumer introduced simply because you noticed higher then usual rate?

**Comment by mv78** [comment]
The rabbitmq consumer utelization rate indicates if consumerrs for
destinatuon are handling the load. If the consumer is slow and messages are
piling up the utelization rate drops below 1. This indicates throughput
problem. There are two qays to solve this: One, make consumer faster. Two,
add more consumers.

With this enhanncment, by exposing utelizatuon rate to autoscaler, we can
tell underlying platform to add more consumers by scaling up.

**Comment by olegz** [comment]
While your assertion is correct within the context of your problem, it does not address any of the concerns I've described in the previous reply. 

The bottom line is it is not the responsibility of the binder to monitor a shared resource. It's simply out of scope of binder's design.   

As Gary pointed out, you can easily do it yourself with a simple rest call to management plugin, providing it is actually installed, which is also not always the case.

**Comment by mv78** [comment]
Right, as i mentioned earlier that i agree that its duable and simple to do
in the context of my own processor but makes spring cloud sstream starter
apps that use rabbitmq binder usless in the case of ability to autoscale. I
would have to enhance all starter apps we use to incorporate workaround. I
was just hoping we could make it a croas cutting concern which i beleve can
be done in the binder.

**Comment by olegz** [comment]
We're not going to proceed with this given the discussion and reasons described above.
It may make sense to bring this up in a RabbitMQ project itself given that what's been requested is metric on rabbit resources (not application resources).
