### ISSUE TITLE
Rabbit Stream Binder does not create kryo dependency which is deprecated but still needed

### ISSUE THREAD

**Issue by maslano** [spring-cloud/spring-cloud-stream-binder-rabbit#174]
Hi!
I am using Spring cloud Finchley.RELEASE and spring boot 2.0.4.RELEASE. I have just upgraded from Edgware and Spring boot 1.5.9.RELEASE. I was using rabbit binder, and the new one seems not working. I am pretty sure I will just make it work by adding a missing dependency explicitly but Im sure its not what is intended.

What I am getting is : java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/io/Input

By doing a comparison dependencies I can see that:
Before:
```
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:1.3.0.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-stream-binder-rabbit:jar:1.3.0.RELEASE:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-binder-rabbit-core:jar:1.3.0.RELEASE:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-codec:jar:1.3.0.RELEASE:compile
[INFO] |     |  \- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
```

After :
```
[INFO] +- org.springframework.cloud:spring-cloud-starter-stream-rabbit:jar:2.0.0.RELEASE:compile
[INFO] |  \- org.springframework.cloud:spring-cloud-stream-binder-rabbit:jar:2.0.0.RELEASE:compile
[INFO] |     +- org.springframework.cloud:spring-cloud-stream-binder-rabbit-core:jar:2.0.0.RELEASE:compile
[INFO] |     +- org.springframework.boot:spring-boot-starter-amqp:jar:2.0.4.RELEASE:compile
[INFO] |     |  \- org.springframework.amqp:spring-rabbit:jar:2.0.5.RELEASE:compile
[INFO] |     |     +- org.springframework.amqp:spring-amqp:jar:2.0.5.RELEASE:compile
[INFO] |     |     \- com.rabbitmq:amqp-client:jar:5.1.2:compile
[INFO] |     \- org.springframework.integration:spring-integration-amqp:jar:5.0.7.RELEASE:compile
```

So It is not adding the kryo dependency anymore. The problem is, that in spring cloud stream:
https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/converter/CompositeMessageConverterFactory.java in line 90 has:
this.converters.add(new KryoMessageConverter(null,true));

And since it is adding a converter it causes Java to fail with noclassdeffounderror. I think that someone deprecated the converters but made the code still required the libraries. I dont think its correct (although I will probably fix it with specyfing that dependency myself)

**Comment by olegz** [comment]
I would look in your POM and see if anything jumps (i.e., some exclusion). While we did deprecated Kryo and Java serialization, we did not remove it and it should available. 
The best way to validate it is to create a new app from [Spring Initializr](https://start.spring.io/) and compare the POMs

**Comment by maslano** [comment]
@olegz I dont have any exclusion in my project, and I am the owner of all parents etc so I am sure
Where is the kryo dependency then? Using my dependency tree I can see that the kryo was never explicitly added as a dependency, but through spring-cloud-stream-codec.

Now in latest version that library is not even in the dependency management:
https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/master/pom.xml
https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/master/spring-cloud-stream-binder-rabbit/pom.xml

yet it was before:

https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/0c6b024dfa0193c47bc42779647a93e7ab14ca3a/pom.xml
https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/0c6b024dfa0193c47bc42779647a93e7ab14ca3a/spring-cloud-stream-binder-rabbit/pom.xml

**Comment by olegz** [comment]
That is why I suggested to create a sample project using Initialzr. I can't see your POMs, thus don't know what is going on, but a sample project created using Initialzr quickly tells me where it supposed to come from:
```
[INFO] com.example:demo-rabbit-174:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-amqp:jar:2.1.0.M3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.1.0.M3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.1.0.M3:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.1.0.M3:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.1:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.11.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:runtime
[INFO] |  +- org.springframework:spring-messaging:jar:5.1.0.RC3:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.1.0.RC3:compile
[INFO] |  \- org.springframework.amqp:spring-rabbit:jar:2.1.0.M3:compile
[INFO] |     +- org.springframework.amqp:spring-amqp:jar:2.1.0.M3:compile
[INFO] |     +- com.rabbitmq:amqp-client:jar:5.4.1:compile
[INFO] |     +- org.springframework:spring-context:jar:5.1.0.RC3:compile
[INFO] |     |  \- org.springframework:spring-expression:jar:5.1.0.RC3:compile
[INFO] |     \- org.springframework:spring-tx:jar:5.1.0.RC3:compile
[INFO] +- org.springframework.cloud:spring-cloud-stream:jar:2.1.0.BUILD-SNAPSHOT:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-validation:jar:2.1.0.M3:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.12:compile
[INFO] |  |  \- org.hibernate.validator:hibernate-validator:jar:6.0.12.Final:compile
[INFO] |  |     +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |  |     +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  |     \- com.fasterxml:classmate:jar:1.4.0:compile
[INFO] |  +- org.springframework.integration:spring-integration-core:jar:5.1.0.M2:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.1.0.RC3:compile
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.2.0.RC1:compile
[INFO] |  |     \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  +- org.springframework.integration:spring-integration-jmx:jar:5.1.0.M2:compile
[INFO] |  +- org.springframework:spring-tuple:jar:1.0.0.RELEASE:compile
[INFO] |  |  +- com.esotericsoftware:kryo-shaded:jar:3.0.3:compile
[INFO] |  |  |  \- com.esotericsoftware:minlog:jar:1.3.0:compile
. . .
```
As you can see it transitively comes from spring-tuple which we also deprecated.

`spring-cloud-stream -> spring-tuple -> kryo-shaded -> . . .`

**Comment by maslano** [comment]
Ok, thank You. I am sorry I was not able to check the initializr, our corporate network is blocking it (no comment). It appears that someone wanted to be clever and uploaded spring-touple to our nexus manually, thus it had an empty dependency section

**Comment by olegz** [comment]
Good! Glad you were able to resolve it. 
Closing it.
