### ISSUE TITLE
Add confirmAckChannelBeanName

### ISSUE THREAD

**Issue by jwomeara** [spring-cloud/spring-cloud-stream-binder-rabbit#178]
Hello, 

I'm trying to create a webservice which has a rest endpoint which publishes a message onto a rabbitmq queue, and waits until receiving a publisher confirm to return a successful status to the caller.  Is this possible using spring cloud stream w/ rabbitmq?  

I see that it is possible to listen on the error channel for a NackedAmqpMessageException, and that works fine in the examples I've put together, but I don't see an obvious way to listen for a positively acked publisher confirm.  

I also understand that if a publisher confirm callback were to be available, it would likely be processed on a separate thread.  For my purposes, that would be ok, as I could have the rest endpoint wait, and poll periodically checking for the publisher confirm.  

Thanks in advance for your help!

**Comment by garyrussell** [comment]
It is not currently possible to get publisher confirms (acks), only nacks (and returns).

The binder currently sends acks to the `nullChannel` (and it's not configurable).

You could hack it with reflection, but it should really be added as a feature.

**Comment by garyrussell** [comment]
See https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/156 for a way to get a reference to the binding's `AmqpOutboundEndpoint` so you can call `setConfirmAckChannel()` to inject a channel.

**Comment by jwomeara** [comment]
The workaround you provided works great, thanks!  This would definitely be a useful feature for our purposes, so we'd love to see it added as a formal feature.  

Regardless, thanks!  This helped a lot!
