### ISSUE TITLE
Anonymous Queues Prefix should be configurable

### ISSUE THREAD

**Issue by Hades32** [spring-cloud/spring-cloud-stream-binder-rabbit#212]
"anonymous." is hard-coded in https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/master/spring-cloud-stream-binder-rabbit-core/src/main/java/org/springframework/cloud/stream/binder/rabbit/provisioning/RabbitExchangeQueueProvisioner.java

This is sub-optimal from an operational perspective, e.g. when trying to analyze which services created a bunch of anonymous queues.

**Comment by olegz** [comment]
Actually I am not sure why would this be useful? The `anonymous` is never used in production type system not with data flow (primary consumer of spring-cloud-stream). So it is primarily used for local testing and demos.
So I am curious as to what's your use case?

**Comment by garyrussell** [comment]
Actually, for example, `spring-cloud-bus` uses anon (auto-delete) queues so that, e.g., config changes are only sent to active applications.

So, I think this is a reasonable request.

**Comment by Hades32** [comment]
We have use cases where we want all running instances to receive an event. (Typically to update distributed caches). We do this with spring cloud stream by not setting a group which in turn leads to anonymous queues.
So, we do use this in production.

**Comment by Hades32** [comment]
Great, thanks for improving this!

As the code hasn't changed much in that place, could you maybe merge this also into the 2.0.x / 2.1.x releases?

**Comment by olegz** [comment]
I've backported it to 2.1.x branch
