### ISSUE TITLE
RabbitExchangeQueueProvisioner should use AnonymousQueue class

### ISSUE THREAD

**Issue by dsteegen** [spring-cloud/spring-cloud-stream-binder-rabbit#245]
The class `RabbitExchangeQueueProvisioner` should make use of the `AnonymousQueue` class of `spring-amqp`. This class has a constructor since version 2.1 that sets the `x-queue-master-locator` argument to `client-local` by default if this argument was not set (see https://github.com/spring-projects/spring-amqp/issues/818 for details).

In method `doProvisionConsumerDestination` replace

```
if (anonymous) {
    queue = new Queue(queueName, false, true, true, queueArgs(queueName, properties.getExtension(), false));
}
```

with

```
if (anonymous) {
    queue = new AnonymousQueue(() -> queueName, queueArgs(queueName, properties.getExtension(), false));
}
```

Additionally, the property should be configurable via the `RabbitCommonProperties` class

**Comment by garyrussell** [comment]
I concur with setting it by default for anon queues, but I am not sure it's worth adding it as a property since the master locator can be set using a policy on the broker.

**Comment by dsteegen** [comment]
> I concur with setting it by default for anon queues, but I am not sure it's worth adding it as a property since the master locator can be set using a policy on the broker.

Agreed. I think it will suffice to just use the `AnonymousQueue` class. I was not aware that the master locator property can be directly set in RabbitMQ.
