### ISSUE TITLE
Support for Rabbitmq delayed queue

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-rabbit#26]
_From @lchayoun on October 5, 2016 14:43_

add support for Rabbitmq delayed queue plugin.
described in:
http://docs.spring.io/spring-amqp/docs/1.6.3.RELEASE/reference/html/_reference.html#delayed-message-exchange
https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/

_Copied from original issue: spring-cloud/spring-cloud-stream#676_

**Comment by sabbyanandan** [comment]
_From @garyrussell on October 6, 2016 17:46_

In addition to configuring the exchange with delay, this will need support in Spring Integration to avoid the binder having to rebuild the message to add the header.

[PR here](https://github.com/spring-projects/spring-integration/pull/1920).

If needed, we should be able to backport this to 4.3.x.

**Comment by lchayoun** [comment]
Backporting to 4.3.x would be great.

**Comment by garyrussell** [comment]
@lchayoun - It's already available in Spring Integration 4.3.5 (but not yet in the binder).
