### ISSUE TITLE
Question about producer confirms

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-cloud/spring-cloud-stream-binder-rabbit#264]
Hi,

First of all, thank you for a great job on spring cloud stream's projects.

I have a question regarding enforcing consistency via producer confirms Rabbitmq feature. 
If I understand correctly Rabbitmq producer is asynchronous. Let's assume we have next two components:
1. http source which should return response to client if request was accepted for processing and stored in queue. It should only return when producer confirms.
2. any processor which should ack message only when producer confirms (otherwise based on a reason why producer does not confirm - message should be nack'ed or requeued).

What is the correct way achieve such behaviors? 
Will transactional support work for both cases?

Otherwise I'm thinking about:
1. http source case -> enable producer confirms named channel (let's say `ackReply`) and create a spring integration gateway with request channel `@Source.inputChannel` and reply channel `ackReply`. Call gateway from rest controller (assuming it will block on gateway or timeout)
2. processor case -> switch to manual ack mode for consumer, enable producer confirms named channel, register handlers for success/failure producer channels and ack/nack/requeu original message.

Thank you,
Artyom

**Comment by garyrussell** [comment]
Transactions will solve both cases.

While transactions are quite expensive, I don't think you will see much improvement when adding the code to wait for the ack/nack. Publisher confirms improve performance when you send many messages and wait for the confirms after doing so. Waiting for a single confirm requires a round trip to the broker, just like transactions.

**Comment by ArtyomGabeev** [comment]
@garyrussell thank you,

It looks like rabbitmq transaction does not fail if message has not beed routed by exchange, am I correct? Here is example:

`topic exchange: routing key - k1 to topic k-topic`

If I send message with routing key k2, I see that exchange stats showing 1 unrouted message, but no exception is throw (which is probably a correct behavior).

One more question regarding transaction: if I have a processor reading and writing to rabbitmq, I assume framework creates two different connections factories for consumer/producer.

So in this case, looks like I need transaction manager only for producer connection factory, am I correct?

Thanks!

**Comment by garyrussell** [comment]
That is correct; transactions don't help with non-routable messages; if you think you might have that condition then you would need to use confirms and returns (the ack is guaranteed to arrive after the returned message is received).

You will need some mechanism to hold up the calling thread (http or container) until the confirm is received. One way to do that would be to put a `Future<?>` in a message header; wait on it and complete the future in the confirm handler.

>I assume framework creates two different connections factories for consumer/producer.

>So in this case, looks like I need transaction manager only for producer connection factory, am I correct?

No; that is not correct; you should enable transactions on both the consumer and producer.

The producer (RabbitTemplate) will send the message on the consumer's channel; when the listener exits normally, the listener container will send the ack (assuming you are using the default auto acks) and then commit the transaction.

**Comment by ArtyomGabeev** [comment]
@garyrussell thank you very much,

I'm closing this issue.
