### ISSUE TITLE
Ability to customize RabbitTemplate in RabbitMessageChannelBinder

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-cloud/spring-cloud-stream-binder-rabbit#265]
Hi,

I've looking on RabbitMessageChannelBinder and looks like there is not way to customize RabbitTemplate for producer.

The reason why I want it to customize is to add sleuth TracingMessagePostProcessor in order to expose additional tags within the span.

Does it sound like an improvement?

**Comment by olegz** [comment]
Possibly, but of a low priority. However if you're willing to contribute, please submit a PR and we'll review

**Comment by ArtyomGabeev** [comment]
Ok, I’ll  try to submit a PR.

Thanks!

**Comment by garyrussell** [comment]
Consider using the ListenerContainerCustomizer as a model. Perhaps PublishingTemplateCustomizer<T>?

**Comment by artembilan** [comment]
After this: https://github.com/spring-projects/spring-integration/pull/3088 and recently introduced `ProducerMessageHandlerCustomizer` this issue can be treated as fixed.
