### ISSUE TITLE
Add Feature to allow setting arbitrary queue arguments 

### ISSUE THREAD

**Issue by miguelchico** [spring-cloud/spring-cloud-stream-binder-rabbit#274]
There are scenarios where arbitrary queue arguments are necessary to be set while queue declaration.

One example is the new RabbitMQ 3.8.x feature: Single Active Consumer which requires an argument into the queue declaration.

Small conversation around that can be found: https://stackoverflow.com/questions/59011707/spring-cloud-stream-rabbitmq-add-queue-argument

**Comment by garyrussell** [comment]
Depends on https://github.com/spring-projects/spring-amqp/issues/1125
