### ISSUE TITLE
Implement single active consumer for rabbit

### ISSUE THREAD

**Issue by ternsip** [spring-cloud/spring-cloud-stream-binder-rabbit#275]
Hi.
I've spotted that RabbitExchangeQueueProvisioner does not have argument for rabbit argument option
x-single-active-consumer
Please add support for that.
I want to pass this via application.yml props.

**Comment by garyrussell** [comment]
This is a duplicate of #274 it will be resolved when Spring AMQP 2.2.2 is released later this week.
