### ISSUE TITLE
Allow Rabbit Streams binding to use Kotlin lambdas

### ISSUE THREAD

**Issue by mzalewski82** [spring-cloud/spring-cloud-stream-binder-rabbit#286]
Currently (version 3.0) binding functional support requires java.util.function types. It would be good to allow Kotlin lambdas to be used directly without the need for these types.

Related issue: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/795

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream #1935](https://github.com/spring-cloud/spring-cloud-stream/issues/1935) via [**ZenHub**](https://www.zenhub.com/)
