### ISSUE TITLE
Investigate the need for explicit import of boot's RabbitAutoConfiguration in RabbitServiceAutoConfiguration

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream-binder-rabbit#289]
Basically because we have an explicit import of  `RabbitAutoConfiguration` in `RabbitServiceAutoConfiguration`
```
        /**
	 * Configuration to be used when the cloud profile is not set. Defer to Spring Boot
	 * auto-configuration.
	 */
	@Configuration
	@Profile("!cloud")
	@Import(RabbitAutoConfiguration.class)
	protected static class NoCloudProfile {

	}
```
. . . explicit exclusion such as `@SpringBootApplication(exclude = RabbitAutoConfiguration.class)` becomes meaningless.

@garyrussell for any relevant input you may have on this would be nice

**Comment by garyrussell** [comment]
Interesting; I have no idea why that's there; seems unnecessary to me.

**Comment by sabbyanandan** [comment]
Is this a duplicate of #187?

**Comment by garyrussell** [comment]
Duplicates #187
