### ISSUE TITLE
Document is not clear, errorChannelEnabled description is missing?

### ISSUE THREAD

**Issue by leighyu1983** [spring-cloud/spring-cloud-stream-binder-rabbit#302]
Could you provide an example of springcloud stream rabbit reliable delivery for producer side? Not quite clear for the description on the [official document](https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/3.1.0.M1/reference/html/index.html#rabbit-prod-props)  Furthermore, cannot find "errorChannelEnabled" property usage or description on the document.  Thanks.

> confirmAckChannel
When errorChannelEnabled is true, a channel to which to send positive delivery acknowledgments (aka publisher confirms). If the channel does not exist, a DirectChannel is registered with this name. The connection factory must be configured to enable publisher confirms.

>Default: nullChannel (acks are discarded).

**Comment by garyrussell** [comment]
Please don't ask the same question in multiple places; it wastes our time and yours.

https://stackoverflow.com/questions/63131155/springcloud-stream-rabbit-reliable-delivery

I will answer there later today.
