### ISSUE TITLE
If Configured, Wait for a Publisher Confirm When republishing to the DLQ

### ISSUE THREAD

**Issue by MarcialRosales** [spring-cloud/spring-cloud-stream-binder-rabbit#310]
**republishToDlq** is sending messages to a dlx using a fire-forget style and right away it acks the `rejected` message. However, specially in clustered environments, it is too risky to send messages without publisher-confirmation. We are at risk of loosing the rejected message. 

Today, RabbitMQ does not use publisher-confirmation to send a rejected message to a dlx. This means, there is a risk (in clustered environments) whereby we could lose messages because RabbitMQ removes the message from the queue right after sending the message. 

Here is where **republishToDlq**  comes very handy if it used publisher-confirm under the covers and only acked the rejected message after we receive an publisher-confirm acknowledgement.

There are corner cases that we need to handle such as:
- what to do if we receive a negative publisher-confirm? Maybe reject+requeue so that we do not lose the message? or retry it again?
- do we want to ensure the message also gets to a queue? i.e. use mandatory flag. 
- how long do we wait for the publisher-confirmation? I guess a configurable timeout should be enough.

**Comment by garyrussell** [comment]
Already implemented by https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/314
