### ISSUE TITLE
spring.io docs still stuck on 2.2.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by Brutus5000** [spring-cloud/spring-cloud-stream-binder-rabbit#312]
Hello there,

we had some confusion as we were missing a property in the official Spring docs. As it turns out the Spring doc for Spring Cloud Stream Binder Rabbit is still stuck on 2.2.0.BUILD-SNAPSHOT.

I'm not sure if this is the right place to report,but it would be great if somebody could have a look at it.

**Comment by garyrussell** [comment]
Where are you getting the link from?

https://spring.io/projects/spring-cloud-stream#learn

then

https://docs.spring.io/spring-cloud-stream/docs/3.0.10.RELEASE/reference/html/

then

https://docs.spring.io/spring-cloud-stream-binder-rabbit/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream-binder-rabbit.html

**Comment by Brutus5000** [comment]
Ah sorry yeah the link would have been handy I guess.
I came from the google search `spring-cloud-stream-binder-rabbit docs`which points me to https://cloud.spring.io/spring-cloud-stream-binder-rabbit/spring-cloud-stream-binder-rabbit.html

**Comment by garyrussell** [comment]
That's unfortunate; the docs were moved.

It's always best to start at https://spring.io/projects

@sabbyanandan @olegz Maybe Trevor could set up some redirects?

**Comment by sabbyanandan** [comment]
Yep, I am on it. I will get the redirects added with @trevormarshall's help.

**Comment by sobychacko** [comment]
The docs issues have been addressed. Closing the issue.
