### ISSUE TITLE
Don't Bind An Existing Queue

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-rabbit#34]
If a queue already exists, we should not bind it with `#`.

See [SO Question](http://stackoverflow.com/questions/41122182/bind-rabbitmq-consumer-using-spring-cloud-stream-to-an-existing-queue).

**Comment by mbogoevici** [comment]
Maybe we should throw an exception if the existing infrastructure doesn't meet the expectations of Spring Cloud Stream ? On one hand we do have requirements for options to configure the routing key, e.g. https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/issues/23 - on the other hand, my concern is that it makes it easy to make things unpredictable (e.g. the behaviour of a group of applications will be understood only if one looks at the way queues are set up - I guess that's okay when using AMQP directly, but I do wonder if it extends to Stream apps).

**Comment by garyrussell** [comment]
@mbogoevici We have talked before about "opening up" the binder config - perhaps it's giving users enough rope to hang themselves with but how about...

    spring.cloud.stream.rabbit.bindings.input.consumer.exchange-type=topic (default)
    spring.cloud.stream.rabbit.bindings.input.consumer.exchange-name= (default = destination)
    spring.cloud.stream.tabbit.bindings.input.consumer.routing-key=# (default for non-partitioned)

Partitions are currently bound with `name-<instanceIndex>` - either we disallow `routing-key` when partitioned, or suffix with `-<instanceIndex>`.

Also, perhaps

    spring.cloud.stream.rabbit.bindings.input.consumer.bind-to-exchange=true (default)
