### ISSUE TITLE
How to control the loading range of producers and consumers

### ISSUE THREAD

**Issue by LiuYawei2019** [spring-cloud/spring-cloud-stream-binder-rabbit#343]
##### The problem background
> Swagger and spring-cloud-stream component is integrated with Gradle 7.1.1 .
`api("io.springfox:springfox-boot-starter:3.0.0")`.  Swagger class `InMemorySwaggerResourcesProvider` To achieve the `SwaggerResourcesProvider` interface,  `SwaggerResourcesProvider`  To achieve the `java.util.function.Supplier` Thus `InMemorySwaggerResourcesProvider` is identified as a producer.      

Isn't that a problem？The GET method through endpoint debugging `InMemorySwaggerResourcesProvider`  is called periodically.

**Comment by LiuYawei2019** [comment]
The application cannot be used as a producer alone. This problem is resolved after the consumer is configured.

**Comment by opcooc** [comment]
What can't I configure individually?
