### ISSUE TITLE
ClassCastException with Batch Listener and republishToDlq

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-rabbit#348]
See https://stackoverflow.com/questions/69740749/spring-cloud-stream-rabbit-binder-error-sending-batch-messages-to-dlq/69741806#69741806

ClassCastException here:

	Message amqpMessage = StaticMessageHeaderAccessor.getSourceData(message);	Message amqpMessage = StaticMessageHeaderAccessor.getSourceData(message);

because the source data is a `List<Message>` for a batch listener.
Consider:

1. Set `republishToDlq` to false by default for a batch listener.
2. Disallow `republishToDlq` for a batch listener.
3. Publish the entire batch to the DLQ (but I doubt this is right for all use cases).

**Comment by sobychacko** [comment]
Issue moved to [spring-cloud/spring-cloud-stream #2332](https://github.com/spring-cloud/spring-cloud-stream/issues/2332) via [**ZenHub**](https://www.zenhub.com/)
