### ISSUE TITLE
Unnecessary binder dependency on spring-cloud-function-deployer

### ISSUE THREAD

**Issue by mteodori** [spring-cloud/spring-cloud-stream-binder-rabbit#357]
When using the binder in typical scenarios the changes introduced in:

https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/commit/8045ff4df97141f3247ff6bb04ab7d6e8aed65fb#diff-b9c597f6e0103eedb2ae7f49eab7a458fccaa3dbc5c3a34a6c60bd17bb2be073R18-R20

add a dependency on spring-cloud-function-deployer which doesn't seem to be needed and requires an explicit exclusion, see: https://github.com/Activiti/activiti-cloud/pull/601/files

would it be possible to remove or at least make optional?

**Comment by sobychacko** [comment]
@mteodori We can certainly look into making that dependency optional. We will update here.

**Comment by sobychacko** [comment]
This is already addressed.
