### ISSUE TITLE
Consider Elimination of autoDeclareContext

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-rabbit#42]
Currently, beans (queues, exhanges, bindings) are added to an internal application context.

Instead, we could add them to the main context and use the default Boot `RabbitAdmin`.

Note that since we wish to ignore declaration exceptions, we would have to set `AbstractDeclarable.ignoreDeclarationExceptions` to `true` since the default rabbit admin does not have it set by default.

https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/pull/41#discussion_r100457141

**Comment by artembilan** [comment]
We can just perform `setIgnoreDeclarationExceptions()` on the injected `RabbitAdmin`.
Not sure that it may be a problem since we are in a "simple" one-function microservice...

**Comment by garyrussell** [comment]
Well, we don't know that for sure - we have no idea what the user might be doing in the app - that's why I added the flag on the `Declarable`s themselves, for exactly this reason.
