### ISSUE TITLE
setting the delivery mode when republishing to the DLQ

### ISSUE THREAD

**Issue by rashtao** [spring-cloud/spring-cloud-stream-binder-rabbit#53]
At the moment there is no way to configure the `delivery_mode` option used by `RepublishMessageRecoverer`: it is always set to `delivery_mode: 1` (not persistent), even if the original message is published with `delivery_mode: 2` (persistent). 

I think avoiding copying the original options has been introduced since Spring AMQP 1.6, as stated in the reference documentation:

> Also starting with version 1.6, the inbound deliveryMode property is no longer mapped to MessageProperties.deliveryMode, it is mapped to MessageProperties.receivedDeliveryMode instead.

But anyways would be nice to have the possibility to configure it.
Furthermore the default `deliveryMode` for normal pubs (http://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_rabbit_producer_properties) is `PERSISTENT`, so it would be anyways more correct to publish the messages keeping that default option.

This is the config I am using:
```text
spring:
  cloud:
    stream:
      bindings:
        input:
          binder: rabbit
          destination: dest
          group: gname
      rabbit:
        bindings:
          dest:
            consumer:
              autoBindDlq: true
              durableSubscription: true
              requeueRejected: false
              republishToDlq: true
            producer:
              deliveryMode: persistent
```

---
ref: http://stackoverflow.com/questions/42769341/spring-cloud-stream-rabbitmq-messages-published-with-delivery-mode-1-when-repub/42769851

**Comment by garyrussell** [comment]
@sabbyanandan - this is a valid feature request - allow setting of the delivery mode on the republished message, but it will need a change to Spring AMQP to support it.

**Comment by garyrussell** [comment]
Actually it doesn't need a Spring AMQP change.
