### ISSUE TITLE
setting the auto binded queue to auto-delete

### ISSUE THREAD

**Issue by marvinrichter** [spring-cloud/spring-cloud-stream-binder-rabbit#54]
Is it possible to set the feature of the auto binded queue to auto-delete?

In my setup I only have one exchange and topic based routing. Currently if their is no consumer left for a queue, the queue will not be deleted and gets full of messages no one may ever read.

**Comment by mbogoevici** [comment]
@marvinrichter Depending on your needs, if you set it as an anonymous consumer (no consumer group) then the queue will be automatically deleted. This wouldn't work if you require multiple competing consumers. If you do need a consumer group then you can use the `durableSubscription` setting - see http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Brooklyn.BUILD-SNAPSHOT/reference/htmlsingle/#_rabbitmq_consumer_properties

**Comment by marvinrichter** [comment]
Ahh cool thanks durableSubscription was the right config.
