### ISSUE TITLE
Use RabbitTemplate properties from Spring Boot auto-configuration

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-binder-rabbit#69]
Moved from https://github.com/spring-cloud/spring-cloud-stream/issues/951:

Quoting @tajdars:

> I’m noticing some unexpected behavior when trying to publish a message to RabbitMQ via Spring Cloud Stream. I’m using a TCP load balancer to balance connections between nodes in the RabbitMQ cluster. I’m testing the situation in which a node goes down but for a brief period the load balancer might still route requests to that node. In that case, the publisher, if routed to the down node fails to establish a connection and throws an exception. This is unexpected because I have spring.rabbitmq.template.retry.enabled: true set, which I expected would cause it to retry even if the connection attempt failed the first time. In fact, if I try using the auto-configured RabbitTemplate directly without Spring Cloud Stream, it is exhibiting the behavior I expect: a WARN log is published for the initial connection failure but it retries and the load balancer routes to the good node, a connection is established, and the message is successfully published.

**Comment by garyrussell** [comment]
Original Gitter: https://gitter.im/spring-cloud/spring-cloud-stream?at=5912d63cac693c532adb003d
