### ISSUE TITLE
rabbitmq consumer pause/resume

### ISSUE THREAD

**Issue by tajdars** [spring-cloud/spring-cloud-stream-binder-rabbit#70]
spring-cloud-stream-binder-rabbit: 1.2.0.M1

I have a requirement to pause/resume (not destroy) rabbitmq consumer(s).
I don't see the corresponding 
org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer
registered as a bean.
(I was thinking of grabbing a reference to SimpleMessageListenerContainer and 
stop/start against it).

Thoughts ?

**Comment by mbogoevici** [comment]
Binding consumers are not currently registered as beans, but calling start() or stop() on the ApplicationContext would start and stop all the active endpoints. Is that something that solves your use case?

**Comment by tajdars** [comment]
Thanx @mbogoevici , We're looking to stop/start specific queue (consumers).

**Comment by mbogoevici** [comment]
Thanks @tajdars - this requires an enhancement to the binder API, allowing the user more control over the input lifecycle. Would you mind closing this and opening an issue in the core? Thank you!

**Comment by tajdars** [comment]
Moved to

https://github.com/spring-cloud/spring-cloud-stream/issues/963
