### ISSUE TITLE
Is there a way to connect queue as exclusive consumer?

### ISSUE THREAD

**Issue by chaeyk** [spring-cloud/spring-cloud-stream-binder-rabbit#80]
org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer has setExclusive() feature.
This is useful when you need to guarantee the order of messages, when there is multiple consumers.

**Comment by artembilan** [comment]
Related SO question: https://stackoverflow.com/questions/45072016/can-rabbitmq-or-spring-cloud-stream-consume-messages-exclusively

**Comment by garyrussell** [comment]
It is not currently supported; we can add it.

**Comment by mbogoevici** [comment]
@chaeyk Do you expect both exclusivity and load balancing, or are you comfortable with all messages being handled by a single instance. From the original question in SO, it seems like you expect some form of load balancing between consumers, but this setting will effectively result in all messages being received by one and only one consumer (as @garyrussell pointed out here: https://stackoverflow.com/a/45081997/809122 )

**Comment by chaeyk** [comment]
What I need is message ordering with multi consumer, so load balancing is not my matter. There are multi consumer because it is included within web api server, and for high availibility.
I worked around by making wrapper of connectionfactory, connection, channel classes. But second consumer's spring application failed to boot because bean initialization failed.

What I really wanted was following.

1. first consumer connect to queue with exclusive option.
2. second consumer try to connect queue, but fails because of exclusive option, and trying to connect periodically.
3. when first consumer dies, second consumer connect to queue.

Simply adding setExclusive() feature would not solve my problem. But I think setExclusive() feature would be useful for someone :)

**Comment by Shohou** [comment]
It would be nice to have some event to be notified when consumer finally connects to queue

**Comment by artembilan** [comment]
Well, there is one already, @Shohou :
```
 * An event that is published whenever a new consumer is started.
 *
 * @author Gary Russell
 * @since 1.7
 *
 */
@SuppressWarnings("serial")
public class AsyncConsumerStartedEvent extends AmqpEvent {
```

**Comment by garyrussell** [comment]
Implement `ApplicationListener<AsyncConsumerStartedEvent>` in a Spring bean to receive the event.

or

    @EventListener
    public void consumerStarts(AsyncConsumerStartedEvent event) { ... }

**Comment by artembilan** [comment]
@Shohou ,

Thank you for feedback!

This issue is closed already with some fix.
If you still have some concerns, please, raise a new one with an appropriate information.
The link to this one would be useful too.
