### ISSUE TITLE
Add an option for queue naming

### ISSUE THREAD

**Issue by sergeyezhov** [spring-cloud/spring-cloud-stream-binder-rabbit#93]
According to [stackoverflow question](https://stackoverflow.com/questions/46327223/spring-amqp-to-spring-cloud-stream-migration-existing-queue):
Problem: the queue name is always `<destination>.<group>`
Solution: add a boolean option `includeDestInQueueName`

**Comment by garyrussell** [comment]
@sabbyanandan - [second request here](https://stackoverflow.com/questions/46327223/spring-amqp-to-spring-cloud-stream-migration-existing-queue/46339868#comment80258364_46339868) I don't think it's a big task if you want to schedule it for the next point release(s).
