### ISSUE TITLE
Add separate ConnectionFactory for producers and consumers to avoid blocking

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-stream-binder-rabbit#95]
When producers overload Broker with huge amount of messages they end up eventually with blocked connection. If we use single `CachingConnectionFactory`, like in case of out-of-the-box auto-configured by Spring Boot, the consumers and producers share really the same cached `Connection`. So, when the last one is blocked by producers, the consumers don't work as well and we have dead lock.

Blocked Connections: https://www.rabbitmq.com/connection-blocked.html.

The suggested solution is to add one more `CachingConnectionFactory` instance into the Binder for producers to let consumers to still read messages from the broker, when producers might be blocked.

**Comment by garyrussell** [comment]
One issue here is if the consumer and producer are transactional, we need the producer to use the same channel; hence the producer has to have the same connection factory as the consumer in that case, so the resource lookup will work properly.
