### ISSUE TITLE
Add event which is fired when consumer connects to the queue

### ISSUE THREAD

**Issue by Shohou** [spring-cloud/spring-cloud-stream-binder-rabbit#98]
Now there is a possibility to connect to queue with consumer in exclusive mode - #80 

When working with such consumers it's now impossible to tell if the consumer is actually connected to the queue or is it waiting when another consumer will disconnect freeing exclusive lock on the queue.

It would be nice to be able to receive some event when consumer connects to the queue and when it disconnects.

What I want to achieve is active/backup instances. When active instance is working with the queue, backup instance simply waits for connection. When we stop active instance, backup instance should start from that point where active instance left. To do that it needs to update status from the database to see what previous active instance have done and the simplest way from my opinion would be to intercept the moment when consumer connects to the queue. That would allow us to do status update before receiving any messages from the queue.

Right now there is already two events - **AsyncConsumerStartedEvent** and **AsyncConsumerStoppedEvent**, but they are fired when consumer is created, not when it connects to the queue. And actually it seems to me they are not working at all, because **RabbitMessageChannelBinder** doesn't set **applicationEventPublisher** to the **SimpleMessageListenerContainer** when it creates one.

**Comment by artembilan** [comment]
I think this is valid request.

Please, raise an appropriate [JIRA](https://jira.spring.io/browse/AMQP) for Spring AMQP project to bring new event type. 

Here on the Rabbit Binder lever only what we can do is indeed `applicationEventPublisher` injection into the `SimpleMessageListenerContainer` internal instances. 

Thank you!

**Comment by Shohou** [comment]
Done - https://jira.spring.io/browse/AMQP-776

Thank you!

**Comment by sabbyanandan** [comment]
This is addressed in 1.3 GA / Ditmars.GA release.
